-- CREATE TABLE CUSTOMER (
-- 	CUST_ID INT PRIMARY KEY,
-- 	CUST_NAME VARCHAR(50) NOT NULL,
-- 	CUST_AGE INT NOT NULL,
-- 	CUST_CITY CHAR(50),
-- )

-- SELECT * FROM CUSTOMER;

-- INSERT INTO CUSTOMER 
-- VALUES 
-- (1, 'ABC', 21, 'PUNE'), 
-- (2, 'DEF', 34, 'MUMBAI'), 
-- (3, 'GHI', 26, 'DELHI');

-- UPDATE CUSTOMER 
-- SET CUST_NAME='XYZ', CUST_AGE=27 
-- WHERE CUST_ID=3;

-- DELETE FROM CUSTOMER 
-- WHERE CUST_ID=3;

-- INSERT INTO CUSTOMER 
-- VALUES 
-- (3, 'GHI', 26, 'DELHI');

-- ALTER TABLE CUSTOMER 
-- ADD CUST_SALARY INT;

-- ALTER TABLE CUSTOMER 
-- DROP COLUMN CUST_SALARY;

-- ALTER TABLE CUSTOMER 
-- ALTER COLUMN CUST_CITY CHAR(50) NOT NULL;

-- ALTER TABLE CUSTOMER
-- ADD CONSTRAINT CK_AGE
-- CHECK (CUST_AGE>=18);

-- ALTER TABLE CUSTOMER
-- DROP CONSTRAINT CK_AGE;

-- SELECT CUST_NAME FROM CUSTOMER;

-- SELECT * FROM CUSTOMER;

-- SELECT DISTINCT CUST_AGE FROM CUSTOMER;

-- SELECT CUST_NAME FROM CUSTOMER 
-- WHERE CUST_CITY='PUNE';

-- SELECT CUST_NAME FROM CUSTOMER 
-- WHERE CUST_CITY='PUNE' AND CUST_AGE=21;

-- SELECT * FROM CUSTOMER 
-- WHERE CUST_CITY='PUNE' AND CUST_AGE>=21;

-- SELECT * FROM CUSTOMER 
-- ORDER BY CUST_AGE ASC;

-- SELECT * FROM CUSTOMER 
-- ORDER BY CUST_AGE DESC;

-- SELECT TOP 2 * FROM CUSTOMER;

-- SELECT * FROM CUSTOMER
-- ORDER BY CUST_ID
-- OFFSET 0 ROWS
-- FETCH NEXT 2 ROWS ONLY;

-- TRUNCATE TABLE CUSTOMER;

-- DROP TABLE CUSTOMER;